# /etc/rsyslog.d/boilerswitch.conf

if ($programname == "alert.py" or
    $programname == "boilerswitch_core.py" or
    $programname == "gpio.py") then {
    action(
        type="omfile"
        File="/var/log/boilerswitch.log"
    )
    stop
}
